package lotto.model

import lotto.constants.*

enum class LottoRank(val count: Int, val winningAmount: Int) {
	FIRST(LOTTO_FIRST_COUNT, LOTTO_FIRST_AMOUNT),
	SECOND(LOTTO_SECOND_THIRD_COUNT, LOTTO_SECOND_AMOUNT),
	THIRD(LOTTO_SECOND_THIRD_COUNT, LOTTO_THIRD_AMOUNT),
	FOURTH(LOTTO_FOURTH_COUNT, LOTTO_FOURTH_AMOUNT),
	FIFTH(LOTTO_FIFTH_COUNT, LOTTO_FIFTH_AMOUNT),
	NONE(LOTTO_NONE_COUNT, LOTTO_NONE_AMOUNT)
}
